/**
 * Dashboard KPIs and Analytics data, derived from MOCK_RECORDS rather than typed out.
 *
 * Deriving matters here. 02-dashboard.md §1 says every KPI on the Dashboard
 * summarizes data generated by later pages, so a hand-written KPI that disagrees
 * with the records list is a bug a judge can find in ten seconds by clicking the
 * card. Everything below counts the same records the Records page shows.
 *
 * The historical trend series is the one exception and is illustrative, because
 * twelve seed records cannot describe several months of activity.
 *
 * TODO: BRD §15 Q-07 is unresolved — whether real manual-inspection baseline data
 * exists. Until it does, treat the trend series as illustrative in any demo claim.
 */

import type {
  AnalyticsData,
  AnomalyAlert,
  CategoryBreakdownEntry,
  ComplianceStatus,
  DashboardAlert,
  KpiMetric,
  RegionBreakdownEntry,
  SourceBreakdownEntry,
  TrendPoint,
  ViolationBreakdownEntry,
} from "@/types";
import { SOURCE_TAGS, VIOLATION_CATEGORY_IDS } from "@/types";

import { MOCK_ACTIVE_RECORDS } from "./records";

const total = MOCK_ACTIVE_RECORDS.length;

function countByStatus(status: ComplianceStatus): number {
  return MOCK_ACTIVE_RECORDS.filter((r) => r.complianceStatus === status).length;
}

const compliantCount = countByStatus("Compliant");
const nonCompliantCount = countByStatus("Non-Compliant");
const pendingCount = countByStatus("Pending");

const percentageOf = (count: number) =>
  total === 0 ? 0 : Math.round((count / total) * 100);

/**
 * The four Dashboard KPI cards.
 *
 * "Pending" counts records whose Verification Status is still Extracted. 02 §2 and
 * 00-README.md §A both insist this means "awaiting verification", not a vague
 * backlog, which is why its hint string says so explicitly.
 */
export const MOCK_KPIS: readonly KpiMetric[] = [
  {
    id: "productsScanned",
    value: total,
    deltaPercentage: 12,
  },
  {
    id: "compliant",
    value: compliantCount,
    percentageOfTotal: percentageOf(compliantCount),
    deltaPercentage: 4,
    routesToStatus: "Compliant",
  },
  {
    id: "nonCompliant",
    value: nonCompliantCount,
    percentageOfTotal: percentageOf(nonCompliantCount),
    deltaPercentage: 9,
    routesToStatus: "Non-Compliant",
  },
  {
    id: "pending",
    value: pendingCount,
    percentageOfTotal: percentageOf(pendingCount),
    deltaPercentage: -3,
    routesToStatus: "Pending",
  },
];

/** Illustrative weekly series. See the file header. */
export const MOCK_TREND: readonly TrendPoint[] = [
  { date: "2026-07-06", compliant: 41, nonCompliant: 18, totalScans: 64 },
  { date: "2026-07-13", compliant: 47, nonCompliant: 21, totalScans: 73 },
  { date: "2026-07-20", compliant: 52, nonCompliant: 19, totalScans: 78 },
  { date: "2026-07-27", compliant: 44, nonCompliant: 26, totalScans: 76 },
  { date: "2026-08-03", compliant: 58, nonCompliant: 23, totalScans: 88 },
  { date: "2026-08-10", compliant: 61, nonCompliant: 29, totalScans: 96 },
  { date: "2026-08-17", compliant: 55, nonCompliant: 34, totalScans: 94 },
  { date: "2026-08-24", compliant: 63, nonCompliant: 31, totalScans: 101 },
  { date: "2026-08-31", compliant: 69, nonCompliant: 38, totalScans: 114 },
];

export const MOCK_VIOLATION_BREAKDOWN: readonly ViolationBreakdownEntry[] =
  VIOLATION_CATEGORY_IDS.map((categoryId) => ({
    categoryId,
    count: MOCK_ACTIVE_RECORDS.reduce(
      (sum, record) =>
        sum + record.violations.filter((v) => v.categoryId === categoryId).length,
      0
    ),
  }));

export const MOCK_CATEGORY_BREAKDOWN: readonly CategoryBreakdownEntry[] =
  Object.values(
    MOCK_ACTIVE_RECORDS.reduce<Record<string, CategoryBreakdownEntry>>(
      (acc, record) => {
        const entry = acc[record.category] ?? {
          category: record.category,
          compliant: 0,
          nonCompliant: 0,
        };
        if (record.complianceStatus === "Compliant") entry.compliant += 1;
        if (record.complianceStatus === "Non-Compliant") entry.nonCompliant += 1;
        acc[record.category] = entry;
        return acc;
      },
      {}
    )
  );

export const MOCK_REGION_BREAKDOWN: readonly RegionBreakdownEntry[] = Object.values(
  MOCK_ACTIVE_RECORDS.reduce<Record<string, RegionBreakdownEntry>>((acc, record) => {
    const entry = acc[record.region] ?? {
      region: record.region,
      totalScanned: 0,
      nonCompliant: 0,
    };
    entry.totalScanned += 1;
    if (record.complianceStatus === "Non-Compliant") entry.nonCompliant += 1;
    acc[record.region] = entry;
    return acc;
  }, {})
);

export const MOCK_SOURCE_BREAKDOWN: readonly SourceBreakdownEntry[] = SOURCE_TAGS.map(
  (source) => ({
    source,
    count: MOCK_ACTIVE_RECORDS.filter((r) => r.source === source).length,
  })
);

/**
 * Dashboard alerts. Severity is chosen per alert, not defaulted to error — 02 §6
 * treats a uniformly red alert list as a defect.
 */
export const MOCK_DASHBOARD_ALERTS: readonly DashboardAlert[] = [
  {
    id: "alert-001",
    severity: "warning",
    message: "MRP Non-Compliance is up 40% against last week.",
    href: "/records?violation=mrp-non-compliance",
  },
  {
    id: "alert-002",
    severity: "error",
    message:
      "Ganga Beverages Ltd has crossed the repeat-violation threshold with 3 Non-Compliant records in 90 days.",
    href: "/manufacturers/mfr-002",
  },
  {
    id: "alert-003",
    severity: "info",
    message: "4 Citizen-Reported submissions are awaiting verification.",
    href: "/records?status=Pending&source=Citizen-Reported",
  },
];

export const MOCK_ANOMALIES: readonly AnomalyAlert[] = [
  {
    id: "anomaly-001",
    title: "Font Size / Readability Failure concentrated in beverages",
    description:
      "Beverage packs account for most Rule 7 failures this month, well above their share of total scans.",
    severity: "warning",
    href: "/records?category=Beverages&violation=font-size-readability-failure",
  },
  {
    id: "anomaly-002",
    title: "Uttar Pradesh scan volume up sharply",
    description:
      "Scan volume in Uttar Pradesh rose against its own four-week baseline. Compliance rate is unchanged.",
    severity: "info",
    href: "/records?region=Uttar%20Pradesh",
  },
];

export const MOCK_ANALYTICS: AnalyticsData = {
  summary: {
    totalScanned: total,
    complianceRatePercentage:
      compliantCount + nonCompliantCount === 0
        ? 0
        : Math.round((compliantCount / (compliantCount + nonCompliantCount)) * 100),
    processingSuccessRatePercentage: 94,
  },
  trend: [...MOCK_TREND],
  violationBreakdown: [...MOCK_VIOLATION_BREAKDOWN],
  categoryBreakdown: [...MOCK_CATEGORY_BREAKDOWN],
  regionBreakdown: [...MOCK_REGION_BREAKDOWN],
  sourceBreakdown: [...MOCK_SOURCE_BREAKDOWN],
  anomalies: [...MOCK_ANOMALIES],
};
