import { beforeEach, describe, expect, it } from "vitest";

import { resetAuditStoreForTests } from "@/lib/server/audit-store";
import {
  getReportForViewer,
  listReports,
  resetReportStoreForTests,
  resolveReportContentRecords,
  resolveScopeRecords,
} from "@/lib/server/report-store";
import { resetPipelineStoreForTests } from "@/lib/server/scan-pipeline-store";

/**
 * Reports are legal/compliance artifacts (13 §4 plan's immutability
 * invariant): a report's frozen rowCount/recordIds must not drift on later
 * reads, its content must not depend on who is currently viewing it, and
 * whether a viewer may see it at all is a separate, viewer-aware check
 * that never touches the frozen data itself.
 *
 * Uses the three seed reports directly rather than a freshly generated run
 * — generation advances over real wall-clock time (`STAGE_DURATION_MS`), so
 * `createReportRun()`'s result has no `.report` yet inside a synchronous
 * test. The seeds are finalized immediately by `ensureSeeded()`, and none
 * of their frozen records are in Maharashtra or generated by a Maharashtra
 * account — exactly the "zero overlap" case worth asserting against.
 *
 *   rpt-5001  generatedByUserId usr-001  recordIds [rec-1002]                       (Uttar Pradesh)
 *   rpt-5002  generatedByUserId usr-003  recordIds [rec-1002, rec-1008, rec-1009]    (UP, UP, Bihar)
 *   rpt-5003  generatedByUserId usr-002  recordIds [rec-1002, rec-1004, rec-1005,
 *                                                    rec-1008, rec-1009]             (UP, Telangana, Delhi, UP, Bihar)
 */
describe("Report immutability and viewer-aware authorization", () => {
  beforeEach(() => {
    resetReportStoreForTests();
    resetPipelineStoreForTests();
    resetAuditStoreForTests();
  });

  it("freezes rowCount and recordIds regardless of who reads them", () => {
    for (const viewerId of ["usr-002", "usr-001", undefined]) {
      const { report } = getReportForViewer("rpt-5003", viewerId);
      expect(report?.rowCount).toBe(5);
      expect(report?.recordIds).toEqual([
        "rec-1002",
        "rec-1004",
        "rec-1005",
        "rec-1008",
        "rec-1009",
      ]);
    }

    const listed = listReports("usr-002").find((r) => r.id === "rpt-5003");
    expect(listed?.rowCount).toBe(5);
  });

  it("blocks a Maharashtra Admin from every seed report — none overlaps her scope and she generated none of them", () => {
    for (const reportId of ["rpt-5001", "rpt-5002", "rpt-5003"]) {
      const { report, blocked } = getReportForViewer(reportId, "usr-004");
      expect(report).toBeUndefined();
      expect(blocked).toBe(true);
    }
    expect(listReports("usr-004")).toHaveLength(0);
  });

  it("always shows a report to the user who generated it, even under the Enforcement Officer own-cases rule", () => {
    // usr-001 is scoped to only his own assigned cases everywhere else, but
    // he generated rpt-5001 himself, so he must see it regardless of scope.
    const { report, blocked } = getReportForViewer("rpt-5001", "usr-001");
    expect(blocked).toBe(false);
    expect(report?.id).toBe("rpt-5001");
  });

  it("shows a National viewer every report unfiltered", () => {
    expect(listReports("usr-002").map((r) => r.id).sort()).toEqual([
      "rpt-5001",
      "rpt-5002",
      "rpt-5003",
    ]);
  });

  it("resolves not-found and blocked as distinct outcomes", () => {
    const notFound = getReportForViewer("rpt-does-not-exist", "usr-002");
    expect(notFound.report).toBeUndefined();
    expect(notFound.blocked).toBe(false);

    const blocked = getReportForViewer("rpt-5001", "usr-004");
    expect(blocked.report).toBeUndefined();
    expect(blocked.blocked).toBe(true);
  });

  it("resolves content through the generating user's own scope, never a different reader's", () => {
    const { report } = getReportForViewer("rpt-5003", "usr-002")!;
    const content = resolveReportContentRecords(report!);
    // rpt-5003's generator is usr-002 (National) — content should equal
    // exactly what resolving its stored scope through usr-002 produces,
    // independent of whichever viewerId was used to look the report up.
    const expected = resolveScopeRecords(report!.scope, report!.generatedByUserId);
    expect(content.map((r) => r.id).sort()).toEqual(expected.map((r) => r.id).sort());
  });
});
